services:
  postgres:
    image: postgres:15-alpine
    container_name: personaltrainr_db
    restart: always
    environment:
      POSTGRES_USER: personaltrainr
      POSTGRES_PASSWORD: personaltrainr
      POSTGRES_DB: personaltrainr
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
