name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck-auth-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/auth-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx prisma generate
      - run: npx tsc --noEmit

  typecheck-workout-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/workout-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx prisma generate
      - run: npx tsc --noEmit

  typecheck-api-gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api-gateway
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx tsc --noEmit

  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
